title: Universidad Técnica de Ambato
logo: https://upload.wikimedia.org/wikipedia/commons/9/93/Escudo_de_la_Universidad_T%C3%A9cnica_de_Ambato.png
description: Manejo y configuración de Software.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
