title: Universidad Técnica de Ambato
logo: <iframe src="https://giphy.com/embed/qgQUggAC3Pfv687qPC" width="480" height="360" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/dommespace-domme-space-programador-qgQUggAC3Pfv687qPC">via GIPHY</a></p>
description: Manejo y configuración de Software.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
